### ISSUE TITLE
update triggers PHP-Warning in WP 5.5

### ISSUE THREAD

**Issue by mcguffin** [wp-cli/language-command#101]
## Bug Report

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).
- [x] Yes, more specifically, I reviewed the guidelines on [how to write clear bug reports](https://make.wordpress.org/cli/handbook/bug-reports/).

**Describe the current, buggy behavior**

At any of these commands ...
```shell
wp language core update
wp language theme update --all
wp language plugin update --all
```

... a PHP-Warning is thrown:
```
PHP Warning:  Declaration of WP_CLI\LanguagePackUpgrader::download_package($package, $check_signatures = false) should be compatible with WP_Upgrader::download_package($package, $check_signatures = false, $hook_extra = Array) in phar:///home/swilkens/bin/wp/vendor/wp-cli/language-command/src/WP_CLI/LanguagePackUpgrader.php on line 51

```

**Provide additional context/Screenshots**

There is a similar issue in core command: https://github.com/wp-cli/core-command/issues/169

```shell
$ wp cli info
OS:	Linux 3.10.0-[NOT_DISCLOSED] #1 SMP [NOT_DISCLOSED] UTC 2020 x86_64
Shell:	/bin/bash
PHP binary:	/[NOT_DISCLOSED]/php
PHP version:	7.4.11
php.ini used:	/[NOT_DISCLOSED]/php.ini
WP-CLI root dir:	phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:	phar://wp-cli.phar/vendor
WP_CLI phar path:	[NOT_DISCLOSED]
WP-CLI packages dir:	[NOT_DISCLOSED]
WP-CLI global config:	
WP-CLI project config:	
WP-CLI version:	2.4.0
```

```shell
$ wp core version --extra
WordPress version: 5.5.2
Database revision: 48748
TinyMCE version:   4.9100 (49100-20200624)
Package language:  de_DE
```

**Comment by wojsmol** [comment]
Hi
This issue is already see https://github.com/wp-cli/language-command/pull/100. You can already test the fix with the WP-CLI nightly version, which you can use via `wp cli update --nightly`.

**Comment by strarsis** [comment]
+1, same issue with `WP-CLI 2.4.0` which should be the latest one at time of writing. Has this been merged and released now?
