### ISSUE TITLE
When running any language command: Error: Requires WordPress 4.0 or greater.

### ISSUE THREAD

**Issue by fabioneves** [wp-cli/language-command#102]
When I try to run multiple language commands I always get the same error:
**_Error: Requires WordPress 4.0 or greater._**

**wp language plugin list --status=installed**

**wp language core list**

Any command that seems to be correct triggers the same error. Any idea of what it could be? Using WP-CLI 2.4.0 and PHP 7.4.12

Tried the same command in different environments, I always get the same error.

**Comment by wojsmol** [comment]
Please post wp core version` output

**Comment by fabioneves** [comment]
wp core version
5.5.3

Although it reports the correct version I found out that the issue lies within the project I'm working on. There's some libraries and vendor packages loading up and looks like that's messing WP.

Closing this, since it's not a bug.

Thanks
