### ISSUE TITLE
Add `--all` flag to `uninstall` commands

### ISSUE THREAD

**Issue by swissspidy** [wp-cli/language-command#122]
## Feature Request

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).

**Describe your use case and the problem you are facing**

The `plugin install` and `theme install` commands support `--all` to quickly install languages for all plugins/themes.

The `uninstall` commands don't support it.

**Describe the solution you'd like**

Adding this flag to the `plugin install` and `theme install` commands would make them more consistent.

**Comment by abhi3315** [comment]
I am taking up this issue.

**Comment by huzaifaalmesbah** [comment]
I completely agree with this suggestion.

**Comment by atoomic** [comment]
I currently have a prototype branch setup using #124 to add `--all` to themes.
I fixed the listing and co issues but I struggle to get my env setup correctly to run unit tests correctly.

Please feel free to grab back that case.
