### ISSUE TITLE
Could not install language pack for plugin

### ISSUE THREAD

**Issue by ernilambar** [wp-cli/language-command#138]
## Bug Report

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).
- [x] Yes, more specifically, I reviewed the guidelines on [how to write clear bug reports](https://make.wordpress.org/cli/handbook/bug-reports/).

**Describe the current, buggy behavior**

I am trying to install language pack for an existing plugin.

**Describe how other contributors can replicate this bug**

`wp language core install ne_NP`

`wp site switch-language ne_NP`

Trying to install plugin language pack for an existing plugin.

`wp language plugin install hello-dolly ne_NP`

Output:

```
Warning: Language 'ne_NP' not available.
Language 'ne_NP' not installed.
Success: Installed 0 of 1 languages (1 skipped).
```

**Describe what you would expect as the correct outcome**

Not sure why just installed language is not detected.

**Let us know what environment you are running this on**

```
OS:     Darwin 22.6.0 Darwin Kernel Version 22.6.0: Tue Nov  7 21:48:06 PST 2023; root:xnu-8796.141.3.702.9~2/RELEASE_X86_64 x86_64
Shell:  /bin/zsh
PHP binary:     /usr/local/Cellar/php@8.2/8.2.15/bin/php
PHP version:    8.2.15
php.ini used:   /usr/local/etc/php/8.2/php.ini
MySQL binary:   /usr/local/bin/mysql
MySQL version:  mysql  Ver 8.3.0 for macos13.6 on x86_64 (Homebrew)
SQL modes:
WP-CLI root dir:        phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:      phar://wp-cli.phar/vendor
WP_CLI phar path:       /Users/nilambarsharma/Sites/staging/app/public/wp-content/plugins
WP-CLI packages dir:    /Users/nilambarsharma/.wp-cli/packages/
WP-CLI cache dir:       /Users/nilambarsharma/.wp-cli/cache
WP-CLI global config:
WP-CLI project config:  /Users/nilambarsharma/Sites/staging/wp-cli.local.yml
WP-CLI version: 2.10.0
```

**Comment by ernilambar** [comment]
Looks like language `ne_NP` for `hello-dolly` is not available. May be we could make message clear.

Current:
`Warning: Language 'ne_NP' not available.`

Improvement:
`Warning: Language 'ne_NP' for plugin 'hello-dolly' not available.`

**Comment by danielbachhuber** [comment]
> May be we could make message clear.

Sure, sounds fine to me.
