### ISSUE TITLE
How to download language without database connection?

### ISSUE THREAD

**Issue by mahnunchik** [wp-cli/language-command#14]
How to download language without database connection?

```bash
$ wp --allow-root core language install ru_RU
Error: Error establishing a database connection. This either means that the username and password information in your `wp-config.php` file is incorrect or we can’t contact the database server at `localhost`. This could mean your host’s database server is down.
```

**Comment by danielbachhuber** [comment]
Hi @mahnunchik,

WP-CLI mirrors the behavior of WordPress core (and uses many of the same internal APIs). Because WordPress core requires a functioning database connection to install languages, WP-CLI too requires a functioning database connection.
