### ISSUE TITLE
support must-use plugins in subdirectories

### ISSUE THREAD

**Issue by chrillep** [wp-cli/language-command#155]
## Feature Request
support installing and updating languages for must use plugins in sub directories

**Describe your use case and the problem you are facing**

cant install or update languages for must use plugins in subdirectories

**Describe the solution you'd like**

feature parity for must-use plugins with non must-use plugins

**Comment by swissspidy** [comment]
How are you adding plugins to subdirectories in mu-plugins exactly?

The thing is, WP-CLI is just using the WordPress native functionality to update languages—and WordPress doesn't support updating/installing languages for mu-plugins in subdirectories. So this sounds more like a feature request for WordPress itself.

**Comment by chrillep** [comment]
You're right ☹️.

For me as an end user its more "stuck between a rock and a hard place"

Can it be solved in WP-CLi?

My acceptance criteria 

- wp language commands should work on mu plugins

**Comment by chrillep** [comment]
Also it's fine if you don't want to solve this ♥️.
But my criteria is still a worthwhile issue 😅.

**Comment by swissspidy** [comment]
Can you give an example of a plugin that you are installing this way?

**Comment by swissspidy** [comment]
Also, what commands have you tried exactly?

I just ran `wp language plugin install jetpack de_DE` (without Jetpack even being installed!) and the language was installed just fine. It should work the same if your plugin is installed but in mu-plugins.

Soo... it seems to already work.

**Comment by chrillep** [comment]
If you can Install/update languages without the plugin even being installed. then Technically my criteria is solved 😀

**Comment by chrillep** [comment]
> Can you give an example of a plugin that you are installing this way?

WooCommerce, yoast from https://wpackagist.org/

**Comment by swissspidy** [comment]
Then I recommend running those commands yourself and if something specific doesn‘t work, let us know and we can look into it. Closing for now since it seems to work already
