### ISSUE TITLE
Change activate command

### ISSUE THREAD

**Issue by swissspidy** [wp-cli/language-command#23]
Currently, there's `wp language core activate` and `--activate` flags for the other commands.

Activating a language is nothing more than `wp option update WPLANG <locale>` and checking whether that language actually exists.

In #21, I started working on subcommands for plugins and themes. Activating a language is a global action per site. One cannot activate language X for plugin A and language Y for plugin B. 

Should `wp language core activate` be renamed to `wp language activate` or `wp language switch`? See https://github.com/wp-cli/language-command/pull/21#issuecomment-354538850

**Comment by swissspidy** [comment]
@schlessera suggested `wp site switch-language ...` today to distinguish this from the `wp language` command which deals with language _files_, not database settings.

**Comment by GaryJones** [comment]
For those looking for it, the `wp site` command is here:

https://github.com/wp-cli/entity-command/blob/master/src/Site_Command.php

**Comment by swissspidy** [comment]
Fixed in #29, where I introduced `wp site switch-language` and adding a deprecation warning to `wp language core activate`
