### ISSUE TITLE
Language lists don't show error on missing arguments

### ISSUE THREAD

**Issue by schlessera** [wp-cli/language-command#27]
I was just playing around with the new language command, but I couldn't get the list to work on a WP 4.7.9 install:

<img width="763" alt="image 2018-01-25 at 8 18 39 am" src="https://user-images.githubusercontent.com/83631/35375860-db2bf97a-01a8-11e8-8f44-c76de95f6aa6.png">

I had the same problem with themes as well.

**Comment by schlessera** [comment]
To give a bit of context, this site has never dealt with any localization, so the site's languages is still set to the standard english.

The problem might just be some value not even being initialized, and therefore the list returning empty. I'll investigate.

**Comment by schlessera** [comment]
Okay, the problem is actually that it would need either one or more plugin names or the `--all` flag. If you provide neither, it shows an empty list. It should in that case throw an error.

**Comment by gitlost** [comment]
Yes I spent quite a bit of time last night trying to write tests for it and failing. I'm thinking that https://github.com/wp-cli/language-command/pull/21 should probably be reverted until these things are ironed out.

**Comment by schlessera** [comment]
I'm already working on it. Will have a PR  soon.

**Comment by gitlost** [comment]
I don't think us both working on the same part of the codebase will work.

https://github.com/wp-cli/language-command/pull/21 just isn't mature or stable enough for now. I think it should be reverted and not be part of 1.5.0.

**Comment by schlessera** [comment]
Okay, you're leading 1.5.0, so it's your call. I thought the command would already be usable (and useful), albeit not perfect. So, either we revert now, or as an alternative, we do the major fixes, release the command as it can already be used, gather feedback, and push a 1.5.1 to bring it closer to perfection.

**Comment by gitlost** [comment]
The problem for me is that it changes the existing stable behaviour of the language-command. It's not a simple addition or non-perfect enhancement. It's a major refactoring.

So I vote revert.

**Comment by gitlost** [comment]
Am removing the bug label as it's now WIP.

**Comment by swissspidy** [comment]
I think I copied this logic from `wp plugin activate`. Running that command without an argument doesn't throw an error either:

```
wp plugin activate
Success: Plugin already activated.
```

**Comment by schlessera** [comment]
You're right, @swissspidy : https://github.com/wp-cli/entity-command/issues/136

**Comment by swissspidy** [comment]
I guess we can re-use most of the logic from https://github.com/wp-cli/extension-command/pull/83/files
