### ISSUE TITLE
Add support for `is-installed` to check if a given language is installed

### ISSUE THREAD

**Issue by ocean90** [wp-cli/language-command#35]
[Core](https://github.com/wp-cli/core-command/blob/19273f7453c23c37cd8d8a23d26cffa7d3ccad21/src/Core_Command.php#L294-L331) has it, [themes](https://github.com/wp-cli/extension-command/blob/0da98cc867606c28298ddb1540a566be25a769d8/src/Theme_Command.php#L690-L717) and [plugins](https://github.com/wp-cli/extension-command/blob/0da98cc867606c28298ddb1540a566be25a769d8/src/Plugin_Command.php#L875-L900) have it, but languages not.

Doesn't seem like there's a specifc reason for not having it. We probably only need to copy parts of the [`install()`](https://github.com/wp-cli/language-command/blob/a015a39/src/WP_CLI/CommandWithTranslation.php#L153-L158) method. Happy to give it a try if it gets accepted.

**Comment by schlessera** [comment]
@ocean90 Yes, that seems to be missing. I will gladly accept a PR for this.

**Comment by ocean90** [comment]
Submitted PR in #36.
