### ISSUE TITLE
Missing docblock for `activate_language()`

### ISSUE THREAD

**Issue by schlessera** [wp-cli/language-command#46]
The `Core_Language_Command` class contains a public method `activate_language()` that does not come with the needed docblock: https://github.com/wp-cli/language-command/blob/v2.0.0/src/Core_Language_Command.php#L321

This throws a warning in the debug output:
```
Debug (commandfactory): No doc comment for activate_language. (0.086s)
D
```

As this method is not meant to be a possible command, it should not be public.

**Comment by swissspidy** [comment]
Fixed by #47.
