### ISSUE TITLE
`language plugin list` for bad plugin slugs should throw warning

### ISSUE THREAD

**Issue by vielhuber** [wp-cli/language-command#86]
Hello!

When I type

```
wp language plugin list foobar
```

I always get an output:

![image](https://user-images.githubusercontent.com/3183737/64069210-82284e00-cc45-11e9-92d2-68ed54e3deef.png)

I can write anything I want:

![image](https://user-images.githubusercontent.com/3183737/64069214-8d7b7980-cc45-11e9-805d-516c937973fa.png)

This should not be the case :-)

**Comment by janw-me** [comment]
A candidate for _good-first-issue_ ?

**Comment by schlessera** [comment]
Ah, it looks like this is a combination of the command not checking for the plugin's existence and WP Core always having a default language for anything.

I guess we should throw warnings for missing plugins and skip them, which would then end up with an empty list if no valid plugin slugs were provided.

**Comment by GeoJunkie** [comment]
I'll take a look at this
