### ISSUE TITLE
WordPress backend shows 1 update but wp language plugin update not

### ISSUE THREAD

**Issue by vielhuber** [wp-cli/language-command#87]
Hello!

When I run

```
wp language plugin update --all
```

I get:

![image](https://user-images.githubusercontent.com/3183737/64069237-db907d00-cc45-11e9-8f19-aab51129e067.png)

But in the backend I clearly see one translation update waiting:

![image](https://user-images.githubusercontent.com/3183737/64069196-3e354900-cc45-11e9-924a-53ca78b338f2.png)

When I inspect if updates are available to this plugin, it shows me that I installed everything for my main language DE:

```
wp language plugin list stops-core-theme-and-plugin-updates
```

![image](https://user-images.githubusercontent.com/3183737/64069229-aedc6580-cc45-11e9-9e35-997ccc652c42.png)

After the update in the WP backend the output is the same. Could it be that WordPress Backend also updates for non active languages and WP CLI does not?

Has this something to do with https://github.com/wp-cli/language-command/issues/84 ?

**Comment by mathsen** [comment]
Same problem here - up to date WP (5.6) updated wp language (theme|plucin|core) via wp-cli and backend shows same as yours -  an available update.
Pretty annoying.

**Comment by danielbachhuber** [comment]
Thanks for the report, folks.

It seems like this issue is a bit stale, so feel free to stop by the `#cli` channel on [WordPress.org Slack](https://make.wordpress.org/chat/) if you'd like help debugging further.
