### ISSUE TITLE
Add deprecation notice to `wp language core activate` help text

### ISSUE THREAD

**Issue by corsonr** [wp-cli/language-command#94]
`wp language core activate` is deprecated and `wp site switch-language` should be used instead.

**Comment by swissspidy** [comment]
A deprecation message is printed when using the command.

It's still helpful to list the command in the help output, even if it's deprecated.

But I think we could add the deprecation hint also to the help text (the docblock)

**Comment by Pathan-Amaankhan** [comment]
Hello @swissspidy @corsonr,

I have raised the [PR](https://github.com/wp-cli/language-command/pull/125) that adds a deprecation hint in `wp language core activate`'s help text.

Please do let me know if any further changes are required.
